version: '3'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile

    ports:
      - "8082:8082
    dns:
      - 8.8.8.8
      - 9.9.9.9

    depends_on:
      - zookeeper
      - db
  zookeeper:
    image: zookeeper
  db:
    image: mysql
